#!/bin/sh

# First get backup tool:
# https://github.com/danielebailo/couchdb-dump

DIR="$(dirname "$0")"/../backup
echo $DIR
couchdb-backup.sh -b -H 127.0.0.1 -d photo-bank -T -f $DIR/photo-bank.json
