#!/bin/sh

# First get backup tool:
# wget https://raw.githubusercontent.com/danielebailo/couchdb-dump/master/couchdb-backup.sh

DIR="$(dirname "$0")"/../backup
~/bin/couchdb-backup.sh -b -H 127.0.0.1 -d photo-bank -T -f $DIR/photo-bank.json
