#!/bin/bash

# 1. Edit line 7 for your local photo export directory
# 2. Add your SSH key to the photo-uploader user on your
#    photo bank server
# 3. Run each time you want to do an import, or run
#    as a cron job every few minutes

cd ~/ForPhotoBank
mkdir -p __done
shopt -s nullglob # Make no JPGs a no-op

for f in *.jpg
do
    scp $f photo-uploader@saturn:_process
    mv $f __done/
done

