#!/bin/sh

keywords=$*
matches=`find media -path "media/[0-9]*" -name "*${keywords}*"`
echo $matches

if [ -n "$matches" ]
then
    # This probably only works on a Mac
    open $matches
else
   echo "No results found for '$keywords'"    
fi
