#!/bin/sh

keywords=$*
matches=`find media -path "media/[0-9]*" -name "*${keywords}*"`

if [ -n "$matches" ]
then
    echo "Photos with keywords:" $keywords "..."
    echo $matches
    # This probably only works on a Mac
    open $matches
else
   echo "No results found for '$keywords'"    
fi
