#!/bin/sh

APPDIR=code/home-photo-bank
BACKUPDIR=/Volumes/CLACKPHOTO2
HOST=saturn4.local

# TODO: Restore database first
rsync -va $BACKUPDIR/backup pi@$HOST:$APPDIR/resources/ 
# Run this by hand on the server
# ssh -A pi@$HOST $APPDIR/resources/tools/restore-mongodb

# Now sync media, thumbs first
rsync -va $BACKUPDIR/media/_thumbs pi@$HOST:$APPDIR/media/ 
rsync -va $BACKUPDIR/media pi@$HOST:$APPDIR/ 


