#!/bin/sh

echo "Start in a screen session."
echo "Once server has started, disconnect from screen with Ctrl-A d"
echo
echo "To connect from your computer:"
echo "lein repl :connect saturn:3001"
echo

cd ~/code/clojure/home-photo-bank/
NREPL_BIND=0.0.0.0 lein run
